import { type ReactNode, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUpRight, CheckCircle2, Circle, CircleDollarSign, ClipboardCheck, KanbanSquare, LockKeyhole, Table2, TrendingUp, Users, type LucideIcon } from 'lucide-react';
import { useLeads } from '../../hooks/useLeads';
import { useDocuments } from '../../hooks/useDocuments';
import { EmptyState, ErrorState, SkeletonLoader } from '../../components/admin/States';
import { canonicalLeadStatuses, leadProgressMap } from '../../lib/status';
import type { Lead, LeadStatus } from '../../lib/supabase';

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
const colors = ['#2f6bff', '#22c55e', '#f59e0b', '#a855f7', '#14b8a6', '#ef4444'];

export function GlassCard({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <div className={`rounded-xl border border-white/10 bg-gradient-to-br from-white/[0.09] to-white/[0.035] shadow-2xl shadow-blue-950/20 backdrop-blur ${className}`}>{children}</div>;
}

function KpiCard({ label, value, trend, icon: Icon }: { label: string; value: string; trend: string; icon: LucideIcon }) {
  return <GlassCard className="p-5"><div className="flex items-start justify-between"><div><p className="text-[13px] font-medium text-blue-100/90">{label}</p><p className="mt-2 text-[30px] font-bold tracking-tight text-white">{value}</p></div><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-600/20 text-blue-300 ring-1 ring-blue-400/10"><Icon size={20} /></span></div><div className="mt-3 flex items-center gap-1.5 text-[12px]"><ArrowUpRight size={14} className="text-emerald-300" /><span className="font-semibold text-emerald-300">{trend}</span><span className="text-slate-400">live</span></div></GlassCard>;
}

function PipelineCard({ lead }: { lead: Lead }) {
  return <Link to={`/admin/leads/${lead.id}`} className="block rounded-lg border border-white/10 bg-white/[0.045] p-3 transition hover:-translate-y-0.5 hover:border-blue-300/30 hover:bg-white/[0.075]"><div className="flex items-start justify-between gap-2"><div><h4 className="text-[13px] font-bold text-white">{lead.business_name}</h4><p className="mt-1 text-[11px] text-slate-400">Owner: {lead.first_name} {lead.last_name}</p></div><span className="grid h-6 w-6 flex-none place-items-center rounded-full bg-slate-700 text-[10px] font-bold text-blue-100">{(lead.assigned_rep || '—').slice(0, 2)}</span></div><p className="mt-2 text-[13px] font-bold text-white">{currency.format(lead.funding_amount_requested)}</p><p className="text-[11px] text-slate-300">Monthly Rev: {currency.format(lead.monthly_revenue)}</p><div className="mt-3 flex items-center gap-2"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-blue-400 to-blue-600" style={{ width: `${leadProgressMap[lead.status] ?? 0}%` }} /></div><span className="text-[10px] text-slate-400">{new Date(lead.created_at).toLocaleDateString()}</span></div></Link>;
}

function PipelineColumn({ stage, leads }: { stage: LeadStatus; leads: Lead[] }) {
  const stageLeads = leads.filter((lead) => lead.status === stage);
  return <GlassCard className="min-w-[235px] p-3"><div className="mb-3 flex items-center justify-between"><h3 className="text-[13px] font-bold text-white">{stage}</h3><span className="rounded-full bg-blue-950/70 px-2 py-0.5 text-[11px] font-semibold text-blue-200">{stageLeads.length}</span></div><div className="space-y-2.5">{stageLeads.slice(0, 3).map((lead) => <PipelineCard lead={lead} key={lead.id} />)}</div>{stageLeads.length > 3 && <p className="mt-3 text-[11px] text-slate-300">+ {stageLeads.length - 3} more</p>}</GlassCard>;
}

export default function Dashboard() {
  const [volumeMode, setVolumeMode] = useState<'requested' | 'funded'>('requested');
  const { data: leads, loading, error } = useLeads();
  const { data: documents } = useDocuments();

  const funded = leads.filter((lead) => lead.status === 'Funded');
  const totals = useMemo(() => ({ requested: leads.reduce((sum, lead) => sum + lead.funding_amount_requested, 0), funded: funded.reduce((sum, lead) => sum + lead.funding_amount_requested, 0) }), [funded, leads]);
  const sourceMix = useMemo(() => Object.entries(leads.reduce<Record<string, number>>((acc, lead) => ({ ...acc, [lead.source || 'Unknown']: (acc[lead.source || 'Unknown'] ?? 0) + 1 }), {})).map(([name, value], index) => ({ name, value, color: colors[index % colors.length] })), [leads]);
  const trend = useMemo(() => [...leads].reverse().slice(-7).map((lead, index) => ({ day: new Date(lead.created_at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }), requested: Number((lead.funding_amount_requested / 1_000_000).toFixed(2)), funded: Number(((lead.status === 'Funded' ? lead.funding_amount_requested : 0) / 1_000_000).toFixed(2)) || index * 0.01 })), [leads]);

  if (loading) return <div className="min-h-screen bg-[#071225] p-6 lg:p-8"><SkeletonLoader label="Loading dashboard from Supabase..." /></div>;
  if (error) return <div className="min-h-screen bg-[#071225] p-6 lg:p-8"><ErrorState message={error} /></div>;
  if (leads.length === 0) return <div className="min-h-screen bg-[#071225] p-6 lg:p-8"><EmptyState title="No applications yet" message="Supabase did not return any leads for the CRM dashboard." /></div>;

  return <div className="min-h-screen bg-[#071225] text-white"><div className="min-w-0 p-5 lg:p-6"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-[26px] font-black tracking-tight">Business Funding Command Center</h1><p className="mt-1 text-[13px] text-slate-400">Live Supabase CRM overview</p></div><div className="rounded-full border border-emerald-400/20 bg-emerald-500/10 px-4 py-2 text-[12px] font-bold text-emerald-200">Production data</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Total Applications" value={String(leads.length)} trend="Supabase" icon={Users} /><KpiCard label="Requested Volume" value={currency.format(totals.requested)} trend="Live" icon={CircleDollarSign} /><KpiCard label="Funded Deals" value={String(funded.length)} trend="Live" icon={TrendingUp} /><KpiCard label="Pending Documents" value={String(documents.filter((doc) => doc.status === 'Pending').length)} trend="Live" icon={ClipboardCheck} /></div>
    <div className="mt-5 flex items-center justify-between"><h2 className="text-[18px] font-bold text-white">Pipeline Overview</h2><div className="rounded-lg border border-white/10 bg-white/[0.05] p-1"><button className="inline-flex h-8 items-center gap-1.5 rounded-md bg-blue-600 px-3 text-[12px] font-bold text-white"><KanbanSquare size={14} /> Kanban</button><button className="inline-flex h-8 items-center gap-1.5 rounded-md px-3 text-[12px] font-bold text-slate-400"><Table2 size={14} /> Table</button></div></div><div className="mt-3 overflow-x-auto pb-1"><div className="grid min-w-[1430px] grid-cols-10 gap-3">{canonicalLeadStatuses.map((stage) => <PipelineColumn stage={stage} leads={leads} key={stage} />)}</div></div>
    <div className="mt-5 grid gap-4 xl:grid-cols-[1.05fr_0.9fr_0.72fr]"><GlassCard className="p-5"><div className="mb-3 flex items-center justify-between"><h3 className="text-[16px] font-bold text-white">Funding Volume Trend</h3><div className="rounded-lg bg-white/[0.06] p-1"><button onClick={() => setVolumeMode('requested')} className={`rounded-md px-3 py-1.5 text-[12px] font-semibold ${volumeMode === 'requested' ? 'bg-blue-600 text-white' : 'text-slate-300'}`}>Requested</button><button onClick={() => setVolumeMode('funded')} className={`rounded-md px-3 py-1.5 text-[12px] font-semibold ${volumeMode === 'funded' ? 'bg-blue-600 text-white' : 'text-slate-300'}`}>Funded</button></div></div><ResponsiveContainer width="100%" height={190}><AreaChart data={trend}><defs><linearGradient id="volume" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#2f6bff" stopOpacity={0.5}/><stop offset="95%" stopColor="#2f6bff" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="day" tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip /><Area type="monotone" dataKey={volumeMode} stroke="#3b82f6" strokeWidth={3} fill="url(#volume)" /></AreaChart></ResponsiveContainer><p className="mt-1 text-[12px] text-slate-400">Live total: {currency.format(totals[volumeMode])}</p></GlassCard><GlassCard className="p-5"><h3 className="text-[16px] font-bold text-white">Source Mix</h3><div className="mt-5 flex items-center gap-5"><ResponsiveContainer width={96} height={96}><PieChart><Pie data={sourceMix} innerRadius={31} outerRadius={48} dataKey="value" stroke="none">{sourceMix.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie></PieChart></ResponsiveContainer><div className="flex-1">{sourceMix.map((item) => <div key={item.name} className="mt-2 flex items-center justify-between gap-2 text-[12px]"><span className="flex items-center gap-2 text-slate-300"><span className="h-2 w-2 rounded-full" style={{ background: item.color }} />{item.name}</span><span className="font-bold text-white">{item.value}</span></div>)}</div></div></GlassCard><GlassCard className="p-5"><h3 className="text-[16px] font-bold text-white">Document Uploads</h3><div className="mt-5 space-y-2">{documents.slice(0, 5).map((doc) => <div key={doc.id} className="flex items-center justify-between gap-2 text-[12px]"><span className="flex items-center gap-2 text-slate-200">{doc.status === 'Approved' ? <CheckCircle2 size={13} className="text-emerald-300" /> : <Circle size={13} className="text-slate-500" />}{doc.doc_type}</span><span className="text-slate-300">{doc.status}</span></div>)}</div><p className="mt-5 flex items-center gap-2 text-[12px] text-slate-300"><LockKeyhole size={13} className="text-emerald-300" /> Sensitive document details remain private</p></GlassCard></div>
    <div className="mt-5"><GlassCard className="p-5"><h3 className="text-[16px] font-bold text-white">Recent Applications</h3><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{leads.slice(0, 6).map((lead) => <PipelineCard lead={lead} key={lead.id} />)}</div></GlassCard></div>
  </div></div>;
}
